package hostelmgmt;
import static com.sun.org.apache.xerces.internal.util.XMLChar.trim;
import hostelmgmt.connection.connection;
import java.io.IOException;
import java.net.URISyntaxException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.xpath.XPathExpressionException;
import org.xml.sax.SAXException;
import utilities.userSession;
import utilities.validator;
//import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author publisy
 */
public class Payment extends javax.swing.JInternalFrame {
    userSession user;
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    int is_active =0;
    
    /**
     * Creates new form jtable
     */
    public Payment(userSession user) {
        initComponents();
        try {
            conn = connection.getConnection();
        } catch (ParserConfigurationException | SAXException | IOException | XPathExpressionException | URISyntaxException ex) {
            Logger.getLogger(Payment.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.user = user;
        this.fillUserTable("SELECT id,fname,lname,paid_upto From member");
        userID.setEditable(false);
        fnameEdit.setEditable(false);
        lnameEdit.setEditable(false);
        dateEdit.setEditable(false);
        totalPay.setEditable(false);
        dueDep.setEditable(false);
        dueRent.setEditable(false);
        dueTotal.setEditable(false);
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jDialog3 = new javax.swing.JDialog();
        jFrame1 = new javax.swing.JFrame();
        canvas1 = new java.awt.Canvas();
        search = new javax.swing.JTextField();
        clearEdit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lnameEdit = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fnameEdit = new javax.swing.JTextField();
        userchkmsg = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        dateEdit = new javax.swing.JTextField();
        userID = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        payTill = new datechooser.beans.DateChooserCombo();
        jLabel14 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        submitEdit = new javax.swing.JButton();
        payRent = new javax.swing.JTextField();
        payDep = new javax.swing.JTextField();
        payOther = new javax.swing.JTextField();
        deduct = new javax.swing.JTextField();
        rent_check = new javax.swing.JCheckBox();
        dep_check = new javax.swing.JCheckBox();
        other_check = new javax.swing.JCheckBox();
        discount_check = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        totalPay = new javax.swing.JTextField();
        dueRent = new javax.swing.JTextField();
        dueDep = new javax.swing.JTextField();
        dueTotal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog3Layout = new javax.swing.GroupLayout(jDialog3.getContentPane());
        jDialog3.getContentPane().setLayout(jDialog3Layout);
        jDialog3Layout.setHorizontalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog3Layout.setVerticalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setClosable(true);
        setIconifiable(true);

        search.setText("Search");
        search.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchFocusGained(evt);
            }
        });
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchKeyTyped(evt);
            }
        });

        clearEdit.setText("CLEAR");
        clearEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearEditActionPerformed(evt);
            }
        });

        jLabel1.setText("First name");

        jLabel2.setText("Last name");

        userchkmsg.setForeground(new java.awt.Color(255, 51, 0));

        jLabel9.setText("Pre_paid upto");

        jLabel8.setText("Member ID");

        payTill.setCurrentView(new datechooser.view.appearance.AppearancesList("Light",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));

    jLabel14.setText("payment_till");

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(userchkmsg, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(lnameEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(fnameEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel14))
                            .addGap(60, 60, 60)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(dateEdit)
                                .addComponent(payTill, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(userID, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addGap(39, 39, 39)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(userID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel8))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(fnameEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel1))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lnameEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel2))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(dateEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel9))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel14)
                .addComponent(payTill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
            .addComponent(userchkmsg, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    jLabel4.setText("Amount due till date :");

    jLabel12.setText("Rent due");

    jLabel16.setText("Total due amount");

    jLabel13.setText("Deposit due");

    userTable.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null}
        },
        new String [] {
            "Title 1", "Title 2", "Title 3", "Title 4"
        }
    ) {
        boolean[] canEdit = new boolean [] {
            false, false, false, false
        };

        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];
        }
    });
    userTable.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            userTableMouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(userTable);

    submitEdit.setText("Submit");
    submitEdit.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            submitEditActionPerformed(evt);
        }
    });

    payRent.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusLost(java.awt.event.FocusEvent evt) {
            payRentFocusLost(evt);
        }
    });
    payRent.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            payRentActionPerformed(evt);
        }
    });

    payDep.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusLost(java.awt.event.FocusEvent evt) {
            payDepFocusLost(evt);
        }
    });

    payOther.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusLost(java.awt.event.FocusEvent evt) {
            payOtherFocusLost(evt);
        }
    });

    deduct.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusLost(java.awt.event.FocusEvent evt) {
            deductFocusLost(evt);
        }
    });

    rent_check.setText("Rent");

    dep_check.setText("Deposit");

    other_check.setText("Other....");

    discount_check.setText("Discount");

    jLabel6.setText("Payment Amount (RS)");

    jLabel10.setText("Total Payment");

    jLabel7.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
    jLabel7.setForeground(new java.awt.Color(153, 0, 153));
    jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel7.setText("PAYMENT INFO");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(submitEdit)
                            .addGap(30, 30, 30)
                            .addComponent(clearEdit)
                            .addGap(111, 111, 111))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(20, 20, 20)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(rent_check))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addComponent(discount_check)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(other_check)
                                            .addComponent(dep_check)))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(deduct, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(payOther, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(payDep, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(payRent, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(totalPay, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(153, 153, 153)))
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addGap(18, 18, 18)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(249, 249, 249))
                    .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap())
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel16)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(dueTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(4, 4, 4))
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(142, 142, 142))
                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dueRent, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dueDep, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGap(33, 33, 33))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(489, Short.MAX_VALUE)))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel12)
                        .addComponent(dueRent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(dueDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(9, 9, 9)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(dueTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 287, Short.MAX_VALUE)
                            .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(38, 38, 38))
                        .addGroup(layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel7)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(47, 47, 47)
                            .addComponent(jLabel6)
                            .addGap(56, 56, 56))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(payRent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rent_check))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(payDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dep_check))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(payOther, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(other_check))
                            .addGap(10, 10, 10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(deduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(discount_check))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel10)
                        .addComponent(totalPay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(clearEdit)
                        .addComponent(submitEdit))
                    .addGap(20, 20, 20))))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(235, Short.MAX_VALUE)))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchFocusGained
        // TODO add your handling code here:
        search.setText("");
    }//GEN-LAST:event_searchFocusGained

    private void searchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyTyped
        // TODO add your handling code here:
        String sq = search.getText();
        String sql = "SELECT id,fname, lname,date From member where fname like '%"+sq+"%'";
        this.fillUserTable(sql);
    }//GEN-LAST:event_searchKeyTyped

    private void clearEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearEditActionPerformed
        // TODO add your handling code here:
        userID.setText("");
        fnameEdit.setText("");
        lnameEdit.setText("");
        dateEdit.setText("");
        payRent.setText("");
        payDep.setText("");
        deduct.setText("");
        payOther.setText("");
        totalPay.setText("");
        dueRent.setText("");
        dueDep.setText("");
        dueTotal.setText("");
        rent_check.setSelected(false);
        dep_check.setSelected(false);
        other_check.setSelected(false);
        discount_check.setSelected(false);
    }//GEN-LAST:event_clearEditActionPerformed

    private void userTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTableMouseClicked
        try{
            int row = userTable.getSelectedRow();
            String Table_click = (userTable.getModel().getValueAt(row, 0).toString());

            String sql = "Select * from member where id =?";
            pst = conn.prepareStatement(sql);
            pst.setString(1,Table_click);
            rs = pst.executeQuery();
            if(rs.next()){
                userID.setText(rs.getString("id"));
                fnameEdit.setText(rs.getString("fname"));
                lnameEdit.setText(rs.getString("lname"));
                dateEdit.setText(rs.getString("paid_upto"));

                String string = rs.getString("paid_upto");
                DateFormat format = new SimpleDateFormat("y-M-d");
                Date date = format.parse(string);
                Date todaydate = new Date();
                
                Calendar startCalendar = new GregorianCalendar();
                startCalendar.setTime(date);
                Calendar endCalendar = new GregorianCalendar();
                endCalendar.setTime(todaydate);
                int diffYear = endCalendar.get(Calendar.YEAR) - startCalendar.get(Calendar.YEAR);
                int diffMonth = diffYear * 12 + endCalendar.get(Calendar.MONTH) - startCalendar.get(Calendar.MONTH);

                double rent, totalrent;
                String proc = "getDataFromID";
                String[] params = { "rate", "1" };
                ResultSet rate_rs = connection.dbSelectProc(proc, params);
                if(rate_rs.next()){
                rent = Double.parseDouble(rate_rs.getString("monthly_rate"));
                totalrent = rent*diffMonth;
                
                dueRent.setText(Double.toString(totalrent));
                ResultSet deposit_rs;
                String deposit_sql = "Select * from deposit where member_id = ?";
                String[] deposit_params = { rs.getString("id") };
                deposit_rs = connection.dbSelect(deposit_sql, deposit_params);
                
                if(deposit_rs.next()) {
                    dueDep.setText("0");
                }
                else {
                    dueDep.setText(rate_rs.getString("deposit_rate"));
                }
                dueTotal.setText(Double.toString(Double.parseDouble(dueDep.getText())+Double.parseDouble(dueRent.getText())));
            
                if(totalrent > 0){
                payRent.setVisible(true);
                rent_check.setVisible(true);
            }
            else{
                payRent.setVisible(false);
                rent_check.setSelected(false);
                rent_check.setVisible(false);
                }
            if(Double.parseDouble(dueDep.getText()) > 0){
                payDep.setVisible(true);
                dep_check.setVisible(true);
            }
            else{
                payDep.setVisible(false);
                dep_check.setSelected(false);
                dep_check.setVisible(false);
                }
            }
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_userTableMouseClicked

    private void submitEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitEditActionPerformed
        String member = (String) trim(userID.getText());
        String date = (String) trim(dateEdit.getText());
        String other = (String) trim(payOther.getText());
        String deduction = (String) trim(deduct.getText());
        String total = Double.toString(calculate_total());
        String rent = (String) trim(payRent.getText());
        String deposit = (String) trim(payDep.getText());
        Integer loginUser = user.getUserId();
        String login = loginUser.toString();
        boolean rentCheck = rent_check.isSelected();
        boolean depCheck = dep_check.isSelected();
        boolean otherCheck = other_check.isSelected();
        boolean discCheck = discount_check.isSelected();
        String fName = fnameEdit.getText();
        String lName = lnameEdit.getText();
        String tName = fName + " " + lName;
        
        if(this.is_active==1){
        }

        String error    =   "";
        validator v = new validator();
        
        if(!rentCheck && !depCheck){
            error += "Please select either rent or deposit <br/>";
        }
        else{
        if(rentCheck && !v.isDouble(rent)) {
            error += "Invalid Rent \n";
        }
        if(depCheck && !v.isDouble(deposit)) {
            error += "Invalid Deposit \n";
        }
        if(otherCheck && !v.isDouble(other)) {
            error += "Invalid other amount \n";
        }
        if(discCheck && !v.isDouble(deduction)) {
            error += "Invalid deduction amount \n";
        }
        }
        if(!v.isDouble(total)) {
            error += "TOTAL as numbers only <br/>";
        }
        if(error.equals("")){
            int rent_id = 0, dep_id = 0, pay_id = 0;
            String otherAmt="0", deductionAmt = "0";
        if(rentCheck){
            try {
                String insertRentSQL = "INSERT INTO rent (member_id,amount,created_by) VALUES (?,?,?)";
                String[] rentparams = {member,rent,login};
                rent_id = connection.dbExecuteReturnID(insertRentSQL, rentparams);
            } catch (SQLException ex) {
                Logger.getLogger(Payment.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if(depCheck){
            try {
                String insertDepSQL = "INSERT INTO deposit (member_id,amount,created_by) VALUES (?,?,?)";
                String[] depparams = {member,deposit,login};
                dep_id = connection.dbExecuteReturnID(insertDepSQL, depparams);
            } catch (SQLException ex) {
                Logger.getLogger(Payment.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if(otherCheck){
            otherAmt = other;
        }
        if(discCheck){
            deductionAmt = deduction;
        }
            
        try {
            String insertPaySQL = "INSERT INTO payment (member_id,pay_date,pay_other,pay_deduct,pay_total,rent_id,deposit_id,created_by) VALUES (?,?,?,?,?,?,?,?)";
            String[] payparams = {member,date,otherAmt,deductionAmt,total, Integer.toString(rent_id),Integer.toString(dep_id),login};
            connection.dbExecute(insertPaySQL, payparams);

            String insertincSQL = "INSERT INTO income (descr,detail,amount,created_by) VALUES ('Others','Payments',?,?)";
            String[] incparams = {total, login};
            connection.dbExecute(insertincSQL, incparams);

            java.util.Date payupto = payTill.getSelectedDate().getTime();
            DateFormat df           = new SimpleDateFormat("MM/dd/yyyy");
            String Sqlpayupto      = df.format(payupto);

            String insertSQL = "Update member set paid_upto =(STR_TO_DATE( ?, '%m/%d/%Y')), modified_by=?,status=1 where id=?";
            String execute_params[] = {Sqlpayupto, login, member};
            
            connection.dbExecute(insertSQL, execute_params);
            
            String printData[] = {tName,deductionAmt, total, otherAmt,rent,user.getUserName() };
//            Printcomponent  p = new Printcomponent();
            Print_receipt i = new Print_receipt(printData);
            i.setVisible(true);
//            p.printComponent(i);
            
            this.ClearField();
            } catch (SQLException ex) {
                Logger.getLogger(Payment.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        else{
            JOptionPane.showMessageDialog(null, error);
        }    
    }//GEN-LAST:event_submitEditActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
    }//GEN-LAST:event_searchActionPerformed

    private void payRentFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_payRentFocusLost
    set_total();
    }//GEN-LAST:event_payRentFocusLost

    private void payDepFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_payDepFocusLost
    set_total();        // TODO add your handling code here:
    }//GEN-LAST:event_payDepFocusLost

    private void payOtherFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_payOtherFocusLost
    set_total();        // TODO add your handling code here:
    }//GEN-LAST:event_payOtherFocusLost

    private void deductFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_deductFocusLost
    set_total();        // TODO add your handling code here:
    }//GEN-LAST:event_deductFocusLost

    private void payRentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payRentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_payRentActionPerformed

//function overloading to pass sql;
  private void fillUserTable(String sql){
        DefaultTableModel dtm = new DefaultTableModel();
        try{
        pst = conn.prepareStatement(sql);
        rs = pst.executeQuery(sql);
        
        dtm.addColumn("id");
        dtm.addColumn("First name");
        dtm.addColumn("Last name");
        dtm.addColumn("paid_upto");
        
        while(rs.next()){
            Object objData[] = new Object[4];
            for(int i = 0; i<4;i++){
                objData[i]= rs.getString(i+1);
            }
            dtm.addRow(objData);
        }
        userTable.setModel(dtm);
        userTable.getColumnModel().getColumn(0).setMinWidth(0);
        userTable.getColumnModel().getColumn(0).setMaxWidth(0);
        }
        
        catch(SQLException e){
            JOptionPane.showMessageDialog(this, e);
        }
    }
  
  private double calculate_total(){
        String other = (String) trim(payOther.getText());
        String deduction = (String) trim(deduct.getText());
        //String total = (String) trim(totalPay.getText());
        String rent = (String) trim(payRent.getText());
        String deposit = (String) trim(payDep.getText());
        boolean rentCheck = rent_check.isSelected();
        boolean depCheck = dep_check.isSelected();
        boolean otherCheck = other_check.isSelected();
        boolean discCheck = discount_check.isSelected();
        double total;
        total = 0;
        
        validator v = new validator();
        
        if(rentCheck && v.isDouble(rent)) {
            total = total + Double.parseDouble(rent);
        }
        
        if(depCheck && v.isDouble(deposit)) {
            total = total + Double.parseDouble(deposit);
        }
        
        if(otherCheck && v.isDouble(other)) {
            total = total + Double.parseDouble(other);
        }
        
        if(discCheck && v.isDouble(deduction)) {
            total = total - Double.parseDouble(deduction);
       }
        return total;
  }
  
  private void set_total(){
      totalPay.setText(Double.toString(calculate_total()));
 }

  private void ClearField(){
    userID.setText("");
        fnameEdit.setText("");
        lnameEdit.setText("");
        dateEdit.setText("");
        payRent.setText("");
        payDep.setText("");
        deduct.setText("");
        payOther.setText("");
        totalPay.setText("");
        dueRent.setText("");
        dueDep.setText("");
        dueTotal.setText("");
        rent_check.setSelected(false);
        dep_check.setSelected(false);
        other_check.setSelected(false);
        discount_check.setSelected(false);
        rent_check.setVisible(true);  
        dep_check.setVisible(true);
        payTill.setSelectedDate(null);
    }
   
          
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Canvas canvas1;
    private javax.swing.JButton clearEdit;
    private javax.swing.JTextField dateEdit;
    private javax.swing.JTextField deduct;
    private javax.swing.JCheckBox dep_check;
    private javax.swing.JCheckBox discount_check;
    private javax.swing.JTextField dueDep;
    private javax.swing.JTextField dueRent;
    private javax.swing.JTextField dueTotal;
    private javax.swing.JTextField fnameEdit;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lnameEdit;
    private javax.swing.JCheckBox other_check;
    private javax.swing.JTextField payDep;
    private javax.swing.JTextField payOther;
    private javax.swing.JTextField payRent;
    private datechooser.beans.DateChooserCombo payTill;
    private javax.swing.JCheckBox rent_check;
    private javax.swing.JTextField search;
    private javax.swing.JButton submitEdit;
    private javax.swing.JTextField totalPay;
    private javax.swing.JTextField userID;
    private javax.swing.JTable userTable;
    private javax.swing.JLabel userchkmsg;
    // End of variables declaration//GEN-END:variables
}
