package hostelmgmt;


import static com.sun.org.apache.xerces.internal.util.XMLChar.trim;
import hostelmgmt.connection.connection;
import java.io.IOException;
import java.net.URISyntaxException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.xpath.XPathExpressionException;
import org.xml.sax.SAXException;
import utilities.passwordHash;
import utilities.userSession;
import utilities.validator;
//import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author publisy
 */
public class User_edit extends javax.swing.JInternalFrame {
    userSession user;
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    int is_active =0;
    /**
     * Creates new form jtable
     */
    public User_edit(userSession user) {
        initComponents();
    try {
        conn = connection.getConnection();
    } catch (ParserConfigurationException | SAXException | IOException | XPathExpressionException | URISyntaxException ex) {
        Logger.getLogger(User_edit.class.getName()).log(Level.SEVERE, null, ex);
    }
    this.fillUserTable("SELECT id,fname,username,role_id FROM users");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        edit_user = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        edit_contact = new javax.swing.JTextField();
        edit_role = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        Submit = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        edit_lname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        edit_fname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        userchkmsg = new javax.swing.JLabel();
        edit_password = new javax.swing.JPasswordField();
        clear_btn = new javax.swing.JButton();
        userId = new javax.swing.JLabel();
        Errormsg = new javax.swing.JLabel();
        password_change = new javax.swing.JCheckBox();
        deleteBtn = new javax.swing.JButton();
        search = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        userTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(userTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        edit_user.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edit_userKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                edit_userKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edit_userKeyTyped(evt);
            }
        });

        jLabel3.setText("Contact no.");

        edit_role.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose Role", "Admin", "Administration", "Account", "Warden" }));

        jLabel1.setText("First name");

        Submit.setText("UPDATE");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 153));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Update User Details");

        jLabel2.setText("Last name");

        jLabel5.setText("User name");

        jLabel8.setText("Role");

        jLabel6.setText("Password");

        userchkmsg.setForeground(new java.awt.Color(255, 51, 0));

        clear_btn.setText("clear");
        clear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btnActionPerformed(evt);
            }
        });

        userId.setText("jLabel9");

        Errormsg.setForeground(new java.awt.Color(255, 0, 51));
        Errormsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Errormsg.setText("error mesg");

        password_change.setText("Change Password");
        password_change.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                password_changeItemStateChanged(evt);
            }
        });
        password_change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_changeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(userId)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Submit)
                                .addGap(27, 27, 27)
                                .addComponent(clear_btn)
                                .addGap(73, 73, 73))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Errormsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(userchkmsg, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(edit_password, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                                    .addComponent(edit_user)
                                    .addComponent(password_change, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                                    .addComponent(edit_fname)
                                    .addComponent(edit_lname)
                                    .addComponent(edit_contact)
                                    .addComponent(edit_role, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(userchkmsg, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edit_fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edit_lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edit_contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edit_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edit_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addComponent(password_change)
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(edit_role, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Errormsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(userId)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Submit)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(clear_btn))))
        );

        deleteBtn.setText("Delete Selected Record");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        search.setText("Search");
        search.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchFocusGained(evt);
            }
        });
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 113, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(29, 29, 29)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteBtn)))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edit_userKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edit_userKeyPressed
        // TODO add your handling code here:
        //checkUser();
    }//GEN-LAST:event_edit_userKeyPressed

    private void edit_userKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edit_userKeyReleased
        // TODO add your handling code here:
        //checkUser();
    }//GEN-LAST:event_edit_userKeyReleased

    private void edit_userKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edit_userKeyTyped
        // TODO add your handling code here:
        // checkUser();
    }//GEN-LAST:event_edit_userKeyTyped

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        String firstname = (String) trim(edit_fname.getText());
        String lastname =(String) trim(edit_lname.getText());
        String phone = (String) trim(edit_contact.getText());
        
        String username = (String) trim(edit_user.getText());
        String Pswd = (String) trim(edit_password.getText());
        Integer role_id =  edit_role.getSelectedIndex();
        String role = role_id.toString();
        String pswd = Pswd;

        if(this.is_active==1){
            pswd = passwordHash.getHash(Pswd);
        }
        String error    =   "";
        validator v = new validator();
        
        if (v.isnull(firstname) || v.validateName(firstname)) {
            error += "ERROR ! Invalid First Name<br>";
        }
        if (v.isnull(lastname) || v.validateName(lastname)) {
            error += "ERROR !Invalid Last Name<br>";
        }
        if(!v.validatePhone(phone)) {
            error += "ERROR !Invalid Phone number <br/>";
        }
        if ( !v.validateUsername(username) || v.isnull(username) ) {
            error += "ERROR ! Invalid Username  <br/>";
        }
        if(!v.validatePassword(pswd)) {
            error += "ERROR !Invalid Password /must be more than 5 characters <br/>";
        }
        if(role_id <1) {
            error += "Please select a role <br/>";
        }
        if(error.equals("")){
                String insertSQL = "UPDATE users SET fName = ?, lName = ?, Contact = ?, username = ?,Password=?, role_id = ? WHERE id = ?";
                String params[] = {firstname, lastname, phone, username, pswd, role, userId.getText()};
                
                try{
                    if(connection.dbExecuteUpdate(insertSQL, params)==1)
                {
                JOptionPane.showMessageDialog(null, "Updated Successfully");
                this.clearField();
                this.fillUserTable("SELECT id,fname,username,role_id FROM users");
                }
                else{
                JOptionPane.showMessageDialog(null, "fail");
            }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, error);
        }
    }//GEN-LAST:event_SubmitActionPerformed
    private void clearField(){
        edit_fname.setText("");
        edit_lname.setText("");
        edit_password.setText("");
        edit_user.setText("");
        edit_contact.setText("");
        edit_role.setSelectedIndex(0);
        password_change.setSelected(false);
        Errormsg.setText("");

    }
    
    private void clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btnActionPerformed
        // TODO add your handling code here:
        edit_fname.setText("");
        edit_lname.setText("");
        edit_password.setText("");
        edit_user.setText("");
        edit_contact.setText("");
        password_change.setSelected(false);
        edit_role.setSelectedIndex(0);
        Errormsg.setText("");

    }//GEN-LAST:event_clear_btnActionPerformed

    private void userTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTableMouseClicked
        // TODO add your handling code here:
        try{
            // enable update button and desable Register button 
            int row = userTable.getSelectedRow();
            String Table_click = (userTable.getModel().getValueAt(row, 0).toString());
            
            String sql = "Select * from users where id =?";
            pst = conn.prepareStatement(sql);
            pst.setString(1,Table_click);
            rs = pst.executeQuery();
            if(rs.next()){
                String fname = rs.getString("fName");
                userId.setText(rs.getString("id"));
                edit_fname.setText(fname);
                edit_lname.setText(rs.getString("lName"));
                edit_contact.setText(rs.getString("Contact"));
                edit_user.setText(rs.getString("username"));
                edit_user.setEditable(false);
                edit_password.setText(rs.getString("Password"));
                edit_role.setSelectedIndex(rs.getInt("role_id"));
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_userTableMouseClicked

    private void searchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchFocusGained
        // TODO add your handling code here:
        search.setText("");
    }//GEN-LAST:event_searchFocusGained

    private void searchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyTyped
        // TODO add your handling code here:
        String sq = search.getText();
        String sql = "SELECT id,fname,username,role_id From users where fname like '%"+sq+"%'";
        this.fillUserTable(sql);
    }//GEN-LAST:event_searchKeyTyped

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
       if(JOptionPane.showConfirmDialog(null, "Are u Sure ?", "Billing System", JOptionPane.OK_CANCEL_OPTION) == 0)
        {
            if(!("".equals(userId.getText()))){
                String uid = userId.getText(); 
                String Sql = "DELETE from users where id=?"; 
                try {
                    pst = conn.prepareStatement(Sql);
                    pst.setString(1,uid);
                    pst.execute();
                    userId.setText("");
                    
                this.fillUserTable("select id,fName,username,role_id from users");
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, ex);
                }
            }
            else{
                deleteBtn.setVisible(false);
            }
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void password_changeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_changeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password_changeActionPerformed

    private void password_changeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_password_changeItemStateChanged
        this.is_active = (password_change.isSelected()) ? 1 : 0;
        if(this.is_active==1){
            edit_password.setEditable(true);
        }else{
            edit_password.setEditable(false);
        }
    }//GEN-LAST:event_password_changeItemStateChanged

//function overloading to pass sql;
  private void fillUserTable(String sql){
        
        DefaultTableModel dtm = new DefaultTableModel();
        try{
        pst = conn.prepareStatement(sql);
        rs = pst.executeQuery(sql);
        dtm.addColumn("id");
        dtm.addColumn("First name");
        dtm.addColumn("UserName");
        dtm.addColumn("Type");
        
        while(rs.next()){
            Object objData[] = new Object[4];
            for(int i = 0; i<4;i++){
                objData[i]= rs.getString(i+1);
            }
            dtm.addRow(objData);
        }
        userTable.setModel(dtm);
        userTable.getColumnModel().getColumn(0).setMinWidth(0);
        userTable.getColumnModel().getColumn(0).setMaxWidth(0);
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(this, e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Errormsg;
    private javax.swing.JButton Submit;
    private javax.swing.JButton clear_btn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField edit_contact;
    private javax.swing.JTextField edit_fname;
    private javax.swing.JTextField edit_lname;
    private javax.swing.JPasswordField edit_password;
    private javax.swing.JComboBox edit_role;
    private javax.swing.JTextField edit_user;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox password_change;
    private javax.swing.JTextField search;
    private javax.swing.JLabel userId;
    private javax.swing.JTable userTable;
    private javax.swing.JLabel userchkmsg;
    // End of variables declaration//GEN-END:variables
}
